### PR TITLE
Changes in Dockerfile 

### LINKED ISSUE #157: Switch fully to docker
Switch the API to completely run using docker.

### PR DESCRIPTION
**Pull request by 90r1ll4**
# Pull Request

## Description

The bun, node js will be installed and file will be create during the build and pm2 is also include now 

## Related Issue

Closes #157 

## Version

Did you remember to update the version number in the package.json file?

- [ ] For a major restructuring, or large changes please bump the the major version number. (ex: 1.x.x)
- [x] For a minor change, bump the minor version number. (ex: x.1.x)
- [ ] For a bug fix, bump the patch version number. (ex: x.x.1)

## Documentation

For _any_ version updates, please verify if the [documentation page]() needs an update. If it does, please [update the in code docs]() to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.
- [x] My contribution DOES require a documentation update.

### CODE REVIEW

**Comment by j-dogcoder** [comment]
@90r1ll4 We use Bun, not Yarn

**Comment by 90r1ll4** [comment]
> @90r1ll4 We use Bun, not Yarn

But in DockerFile it was setup to use yarn, Should i rewrite it using bun?

**Comment by j-dogcoder** [comment]
Yes please!

**Comment by 90r1ll4** [comment]
@j-dogcoder re-wrote dockerfile added pm2 bun e.t.c , no errors in dockerfile , can't test it due to creds.
image

**Comment by j-dogcoder** [comment]
I will test that now.

**Comment by 90r1ll4** [comment]
@j-dogcoder sure, let me know if any issue

**Review by j-dogcoder — APPROVED** [review]

**Comment by 90r1ll4** [comment]
@j-dogcoder thanx

**Pull request merged**
